### ISSUE TITLE
R markdown Chunk names

### ISSUE THREAD

**Issue by fluby** [lwasser/NEON-Data-Skills#31]
Hey Leah,
I noticed in Intro-HDF5-R.Rmd that the r chunks don't have descriptive names. These help one navigate the chunks easily in the drop-down menus in Rstudio. Did you intentionally omit due to capability issues with the website (wild guess)? If you like I can add in some names into the Rmd file and send a pull request. Just let me know. 

Thanks!
Kate

**Comment by lwasser** [comment]
Hi -- PR away. I'm just learning RMD and i ended up adding them to one of the activities because i noticed when i rendered to .md it named the files based upon the chunk name :) but i didn't know to do it until then. Thanks!!

**Comment by lwasser** [comment]
oh and by pr i meant - pull request away :+1:

**Comment by lwasser** [comment]
Thanks! i'm closing this issue. appreciate the help and feedback!
