### ISSUE TITLE
downloading files prior to the workshop - NEON-HDF5-HyperspectralImagery-In-R/

### ISSUE THREAD

**Issue by scelmendorf** [lwasser/NEON-Data-Skills#39]
Very minor issue, but it's a little weird how some of the files to download are in the pre-workshop materials/prep area, and others are inside the individual half hour lessons.  Maybe put all up front or all inside the lessons?  I think people could get confused thinking they already downloaded the stuff they need.  Or didn't.

**Comment by scelmendorf** [comment]
And another minor issue, but you have it called 'spatialInfo' in the code but 'spatial info' in the explanatory text.  If you have the patience, I'd rename the map info to mapInfo, and then change the text to match. (i heart camelCase)
Either way, consistency is nice if possible

**Comment by scelmendorf** [comment]
Continuing on the very picky thread - you have a typo here:
'Metadata and importa concepts associated with multi-band (multi and hyperspectral) rasters'

**Comment by scelmendorf** [comment]
More minor wording comments  - can you change this:
'Remember that the metadata for the Reflectance dataset designated 15,000 as data ignore value. Thus, let’s set all pixels with a value > 14,999 to NA (no value). If we do this, R won’t try to render these pixels.'
 to 
'Thus, let’s set all pixels with a value = 15000 to NA'

because that matches what the code does?

**Comment by scelmendorf** [comment]
Also, the code for the above needs a 2nd equal sign, should be
b342[b342 == 15000] <- NA
to make it into a logical for the subset/replace

**Comment by scelmendorf** [comment]
Typo here:
 'For example, in the case of ur data'

**Comment by scelmendorf** [comment]
So - this seems confusing to me:
#We need to transpose x and y values in order for our final image to plot properly
b34<-t(b34)
image(log(b34))
 
Because transposing it still doesn't make it plot properly.  Should we leave this out and get to it later?

Also - I think this is not quite right:
 Data Tip: Transpose in HDF5 view, notice that there are three data dimensions for this file: Bands x Rows x Columns. However, when R reads in the dataset, it reads them as: Columns x Bands x Rows. The data are flipped. We can quickly transpose the data to correct for this using the t or transpose command in R.

Doesn't h5read read in columns x rows x bands, but then rs indexing puts this in as rows, cols, bands?

**Comment by scelmendorf** [comment]
How do you know this?  'The lower left hand corner is located at mapInfo[4:5]'??

**Comment by lwasser** [comment]
Hey @scelmendorf i'll take a closer look at these things tomorrow or this evening depending. Per the downloads i tried to put the data in there twice. Each individual lesson should be stand alone so users can download the data there. but the workshops should have it all in the workshop page. Did i miss something on the workshop page?? Thanks!!

**Comment by lwasser** [comment]
hey @scelmendorf can you please provide an example of where the data were in one or the other but not both?  http://neondataskills.org/Data-Workshops/NEON-HDF5-HyperspectralImagery-In-R/ there is one file here to download and it also appears on each lesson page. But if it's missing somewhere i can add it. i have a lot of pages on this site. thank you!

**Comment by lwasser** [comment]
Also - did you fix some of the things above in your PR ?

**Comment by scelmendorf** [comment]
Sorry! I didn't fix anything in the text, just the code (because I spaced on which you wanted us to fix), so I put all the changes to the code in the pull request and all the comments on text in the issue.

**Comment by lwasser** [comment]
ok cool -- i think i've gotten most of it. I think the transpose is confusing but it's right. The data come in column row and wavelength. Some programs (like IDL) read in that order i can only imagine the H5 tools read in that order but i need to followup. 

The raster different is a raster starts most often in the LOWER LEFT hand corner whereas R reads from the top down (versus bottom up). it's super weird but you need to transpose and then read it into a raster to get it right. it doesn't work any other way.  thanks for all of the feedback. i think i've fixed everything.
